
import { PrismaClient } from '@prisma/client';
import { ClinicalEngineService } from './ClinicalEngineService';
import { StartSessionDto, AnswerDto } from './clinical.dto';
import { ClinicalTreeGenerator } from './ClinicalTreeGenerator';
import { MOCK_DENGUE_SPEC } from './test_generator';

const prisma = new PrismaClient();

async function runApiTest() {
    console.log('🧪 Starting Clinical API Integration Test (Manual)...');

    // 1. Setup Data: Ensure Active Tree Exists
    console.log('📝 Seeding Mock Tree...');

    // A. Ensure User exists
    let user = await prisma.user.findFirst({ where: { email: 'mock_clin@test.com' } });
    if (!user) {
        console.log('creating mock user...');
        try {
            user = await prisma.user.create({
                data: {
                    email: 'mock_clin@test.com',
                    // No password field in User model
                    fullName: 'Mock Clinical User',
                    role: 'ADMIN',
                    status: 'ACTIVE',
                    phoneNumber: '081234567890'
                }
            });
        } catch (e) {
            console.warn('User creation failed (likely unique constraint), fetching existing...', e.message);
            user = await prisma.user.findFirst();
        }
    }
    if (!user) throw new Error('Failed to get a user for test');


    // B. Ensure Disease exists
    const diseaseId = 'DENGUE';
    await prisma.clinicalDisease.upsert({
        where: { id: diseaseId },
        update: {},
        create: {
            id: diseaseId,
            name: 'Dengue Mock Disease',
            description: 'Mock data for API test'
        }
    });

    // C. Generate Nodes
    const nodes = ClinicalTreeGenerator.generateTreeNodes(MOCK_DENGUE_SPEC);

    // D. Upsert Tree
    // We want a clean test, so delete existing active tree for this disease
    await prisma.clinicalDecisionTree.deleteMany({
        where: {
            diseaseId: diseaseId,
            version: 'v1-api-test'
        }
    });

    const tree = await prisma.clinicalDecisionTree.create({
        data: {
            diseaseId: diseaseId,
            version: 'v1-api-test',
            clinicalSpec: MOCK_DENGUE_SPEC as any,
            treeNodes: nodes as any,
            specHash: ClinicalEngineService.hashSpec(MOCK_DENGUE_SPEC),
            isActive: true,
            createdBy: user.id,
            commitNote: 'Auto-generated by test_clinical_api_manual'
        }
    });
    console.log('✅ Mock Tree Created:', tree.id);

    // Instantiate Service
    const service = new ClinicalEngineService(prisma as any);

    // 2. Test Start Session
    console.log('\n🚀 Testing START SESSION...');

    // Helper to get valid child/device
    let child = await prisma.child.findFirst();
    if (!child) {
        console.log('creating mock parent/child...');
        // Need parent first.
        let parentUser = await prisma.user.findFirst({ where: { role: 'PARENT' } });
        if (!parentUser) {
            try {
                parentUser = await prisma.user.create({
                    data: {
                        email: 'parent@test.com',
                        // No password
                        fullName: 'Mock Parent User',
                        role: 'PARENT',
                        status: 'ACTIVE'
                    }
                });
            } catch (e) {
                parentUser = await prisma.user.findFirst();
            }
        }
        if (!parentUser) throw new Error('No parent user found');

        // Parent Profile
        let parentProfile = await prisma.parent.findFirst({ where: { user: { id: parentUser.id } } });
        if (!parentProfile) {
            // Need unique parentId (userId)
            parentProfile = await prisma.parent.create({
                data: {
                    parentId: parentUser.id,
                }
            });
        }

        child = await prisma.child.create({
            data: {
                parentId: parentProfile.id,
                fullName: 'Mock Child',
                birthDate: new Date('2022-01-01'),
                gender: 'M',
            }
        });
    }

    let device = await prisma.device.findFirst();
    if (!device) {
        console.log('creating mock device...');
        device = await prisma.device.create({
            data: {
                deviceUuid: 'mock-device-' + Date.now(),
                name: 'Mock Device',
                status: 'AVAILABLE'
            }
        });
    }

    const startDto: StartSessionDto = {
        sessionId: 'dummy-session-uuid',
        deviceId: device.id,
        diseaseIds: [diseaseId]
    };

    const sessionRes = await service.startSession(startDto);
    console.log('✅ Session Started:', sessionRes.sessionId);
    console.log('   Initial Nodes:', sessionRes.nodes);

    if (sessionRes.nodes.length !== 1 || sessionRes.nodes[0].nodeId !== 'dengue__entry_gate') {
        throw new Error('Unexpected initial nodes: ' + JSON.stringify(sessionRes.nodes));
    }

    // 3. Test Answer (Correct)
    console.log('\n📝 Testing SUBMIT ANSWER (Valid)...');
    const answerDto: AnswerDto = {
        sessionId: sessionRes.sessionId,
        nodeId: 'dengue__entry_gate',
        answer: true // Yes to fever
    };

    const nextRes = await service.submitAnswer(answerDto);
    console.log('✅ Next Node:', nextRes);

    if (!nextRes.nextNode || !nextRes.nextNode.nodeId.includes('dengue__')) {
        throw new Error('Expected next node from Dengue tree');
    }

    // 4. Test Answer (Invalid Node)
    console.log('\n🛡️ Testing SUBMIT ANSWER (Invalid Node)...');
    try {
        await service.submitAnswer({
            ...answerDto,
            nodeId: 'fake_node_id'
        });
        throw new Error('Should have failed with Forbidden/NotFound');
    } catch (e) {
        console.log('✅ Correctly rejected invalid node:', e.message);
    }

    // 5. Cleanup (Optional, but good for idempotency)
    // await prisma.session.delete({ where: { sessionUuid: sessionRes.sessionId } });

    console.log('\n🎉 API LOGIC VERIFIED!');
}

runApiTest()
    .catch(e => {
        console.error('\n❌ TEST FAILED:', e);
        process.exit(1);
    })
    .finally(async () => {
        await prisma.$disconnect();
    });
